FROM moledzki/python
MAINTAINER Maciej Olędzki <maciej.oledzki@gmail.com>

RUN apt-get update
RUN apt-get install -y python-psycopg2

RUN pip install robotframework robotframework-selenium2library robotframework-databaselibrary
