FROM moledzki/ubuntu
MAINTAINER Maciej Olędzki <maciej.oledzki@gmail.com>

# Python basics
RUN apt-get install -y --fix-missing python python-pip python-setuptools
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
