CREATE ROLE $POSTGRESQL_USER LOGIN PASSWORD '$POSTGRESQL_PASS' SUPERUSER VALID UNTIL 'infinity';
CREATE DATABASE $POSTGRESQL_DATABASE WITH OWNER = $POSTGRESQL_USER ENCODING = 'UTF8' CONNECTION LIMIT = -1;
