ALTER SCHEMA public OWNER TO $POSTGRESQL_USER;
CREATE EXTENSION IF NOT EXISTS ltree SCHEMA pg_catalog VERSION '1.0';
CREATE EXTENSION IF NOT EXISTS pg_trgm;
ALTER EXTENSION pg_trgm SET SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS plpgsql;
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS tsearch2;
